### ISSUE TITLE
[Request] Add details on AWS emulation

### ISSUE THREAD

**Issue by cc189** [JetBrains/kotless#100]
When you talked `AWS emulation` in the [README](https://github.com/JetBrains/kotless#local-start), what exactly are you referring to? Can you give some more details?

I have the gradle port config:
```gradle
kotless {
    extensions {
        local {
            port = 4566
            useAWSEmulation = true
        }
    }
}
```

And tried some possible `AWS emulation`:
- [Localstack in docker from Github/Localstack](https://github.com/localstack/localstack)
`docker run --rm -p 4566:4566 localstack/localstack -e "SERVICES=dynamodb"`

- [DynamoDB in docker from AWS doc](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html)
```yaml
version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:4566"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
```

I was able to talk with DynamoDB with `aws-cli`:
```sh
# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/getting-started-step-1.html
aws dynamodb create-table \
    --endpoint-url http://localhost:4566 \
    --table-name Music \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
    --provisioned-throughput \
        ReadCapacityUnits=10,WriteCapacityUnits=5
```

But I get error message from Ktor API call:
```
com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: 
Cannot do operations on a non-existent table (
  Service: AmazonDynamoDBv2; 
  Status Code: 400; 
  Error Code: ResourceNotFoundException; 
  Request ID: xxxx; 
  Proxy: null
)

```
